### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by jesusrivas89** [andreaswilli/meta-grabber#11]
I like your program is very fast, but I see a problem does not rename the subtitles .srt, .ssa, .ass. There would be a way for you to include in future versions that renames the subtitles as well? otherwise excellent your work.

**Comment by andreaswilli** [comment]
Glad you like it.
I have not thought about external subtitles so far, will look into it once I find some time.
In the meantime you can use this workaround:
- Change the `included file types` setting to match the file extension of your subtitles
- Open and rename your subtitles as if they were video files

**Comment by jesusrivas89** [comment]
> Glad you like it.
> I have not thought about external subtitles so far, will look into it once I find some time.
> In the meantime you can use this workaround:
> 
> * Change the `included file types` setting to match the file extension of your subtitles
> * Open and rename your subtitles as if they were video files

Thanks @andreaswilli
