### ISSUE TITLE
TheTVDB.com integration

### ISSUE THREAD

**Issue by gelsas** [andreaswilli/meta-grabber#2]
Hello,

I just found your application and I think it is an awesome tool. 
It was working perfectly for a few tv shows but now I have a rather special one it is called:
Rosamunde Pilcher

After searching online it seems that thetvdb.com has an almost complete set of Metadata for the show (142 episodes). TheMovieDB only got 5 or 6. 

(I think for tvshows thetvdb is more complete (also in terms of other languages it seems to have more translations out of my experience)

Would it be possible to add thetvdb.com aswell?

**Comment by andreaswilli** [comment]
Hi, thanks for using my tool. Glad to hear you like it.

So far I've never had trouble finding what I was looking for. But I guess I just didn't try any special or less known tv shows. 😄
I'll definitely have a look at the API of thetvdb.com.

Besides, how did you get aware of Meta grabber?

**Comment by gelsas** [comment]
I love it! Easy UX. With great matching results.

I was actively searching on github for tv show renaming projects

If you want that more people can find this more easily, then you need to optimize the description of this repo. 

Is should include the words in this order: "rename tv shows" and if possible also "TV Show Renamer" (those are the most used search terms when people are looking for such software)

Yes normally TheMovieDB was always enough for me.

For older tv shows or tv shows which are only available in different languages (e.g. spanish, french, german) thetvdb always worked better for me because it seems to have a lot more localized metadata etc.

**Comment by andreaswilli** [comment]
I updated the tags of the repo based on your suggestions. 👍
I'd appreciate it if you could recommend this to some people who might also enjoy it. 🔥

The next update will include some more UI/UX improvements (loading indicators, animations, icons).

**Comment by andreaswilli** [comment]
TVDB integration is part of the 0.1.5 update. 🎉
Please let me know if it works for you.

**Comment by gelsas** [comment]
Worked completely perfect. Thank you so much!
