### ISSUE TITLE
Support for directory in file name template

### ISSUE THREAD

**Issue by sterys** [andreaswilli/meta-grabber#38]
Hi!
I really like the tool but I think that it would be even better if it supported to give directory in the file name template.

I think that is easier to use and make more sense than having some basic support for template for the output dir which only support one tag at the moment.

For converting series to be as plex want them I could then write

`{show_name} ({year})/Seson {season_no}/{show_name} ({year}) - S{season_no} E{episode_no} - {episode_name}`

I suggest to support both **/** and **\\** as dir separator to work for both windows and linux users. 

I also suggest to deprecate the template handling for the output dir since that would no longer be needed.

**Comment by andreaswilli** [comment]
Hi, glad you like it!

Allowing `/` in the file name to support season folders would certainly be an option.

To better understand your usecase it would be helpful if you could provide an example of the file structure in your source and destination folders.

**Comment by sterys** [comment]
What I am doing is that I do rip some dvds with handbrake and then rename them with Meta Grabber to work well with an Plex server.

The source directory is either flat with all files from the ripped dvs or an directory per ripped dvd. Hence the directory structure for the source does not need to follow the one for the target.

So far I have ripped one season at a time to make it easier to map files to episode in Meta Grabber.

So my source dir is 
`~/HandBrake/`

and the root of the destination dir is
`/shared/video/series/`

Where I want an structure like this
```
.
└── Coupling (2000)
    └── Season 01
        ├── Coupling (2000) - s01e01 - Flushed.mp4
        ├── Coupling (2000) - s01e02 - Size Matters.mp4
        ├── Coupling (2000) - s01e03 - Sex, Death  Nudity.mp4
        ├── Coupling (2000) - s01e04 - Inferno.mp4
        ├── Coupling (2000) - s01e05 - The Girl with Two Breasts.mp4
        └── Coupling (2000) - s01e06 - The Cupboard of Patricks Love.mp4
```

Hence the
`{show_name} ({year})/Seson {season_no}/{show_name} ({year}) - S{season_no} E{episode_no} - {episode_name}`

**Comment by andreaswilli** [comment]
Thanks for clarifying.

I think your proposal makes sense. I'll see when I have time to work on it.

**Comment by andreaswilli** [comment]
Please update to [v1.0.0](https://github.com/andreaswilli/meta-grabber/releases/tag/v1.0.0) and let me know if it works.
