### ISSUE TITLE
Creating new folder due to special characters?

### ISSUE THREAD

**Issue by TokerX** [andreaswilli/meta-grabber#48]
I have the output folder setting set to none, but earlier while I was renaming files in a parent folder called "Jeeves & Wooster" a new folder got created called "Jeeves   Wooster". So that probably has got to do with the ampersand (although I'm not sure how an an ampersand would cause any issues)?

And now, while doing Cunk on Earth, it created a new folder with the episode title (well, most of it) with a file in it called Off.mkv for the second episode which is called Faith/Off. This one is a lot clearer why it would do that of course, think the forward slash is part of the path (and file names can't contain slashes of course).

So a check for special characters in filenames is probably needed.

**Comment by andreaswilli** [comment]
Thanks for reporting this issue.

Looks like the handling of special characters could use some work, I'll look into it.

**Comment by andreaswilli** [comment]
The issues should be fixed in version [1.0.2](https://github.com/andreaswilli/meta-grabber/releases/tag/v1.0.2).
