### ISSUE TITLE
Switch from alphabetical sorting to natural number sorting?

### ISSUE THREAD

**Issue by altano** [andreaswilli/meta-grabber#50]
Great app, thank you for making it.

It looks like the sort (and therefore the episode matching) is sub-ideal given the use case of the app. It is using alphabetical sorting and not natural number sorting (https://en.wikipedia.org/wiki/Natural_sort_order), so 1 is followed by 10, and episode 9 is the last one:

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/1009/220832083-b06ef49e-918a-4c60-8479-68dea24afd8f.png">

Ideally, this app could switch to natural number sorting (like macOS' Finder) so it would work without my having to rename the episodes to have 0 padding?

**Comment by andreaswilli** [comment]
Haven't run into this issue so far, but switching to natural sorting makes sense to me.
Don't know when I will get to it, though.

**Comment by andreaswilli** [comment]
Contributions are welcome, btw.

**Comment by andreaswilli** [comment]
Released in version 1.1.0
