### ISSUE TITLE
Windows: Can't rename

### ISSUE THREAD

**Issue by SirFireNewt** [andreaswilli/meta-grabber#9]
Not sure if I'm doing something wrong but attempting to use this tool on a second drive in windows, in this case D:, doesn't appear to work properly.

`Output directory could not be created: Error: ENOENT: no such file or directory, mkdir 'C:\Users\newt\AppData\Local\Programs\meta-grabber\D\media\show\season xx'`

This happens with both a specific output dir on the 2nd drive, and blank to leave the files as is  
I moved the tool to D: and got the same error with the path starting with the new location of the files.  
so this might be an issue with the windows version itself, I was unable to test when both the program and video files are on the same drive however

**Comment by andreaswilli** [comment]
Hey there, thanks for using Meta Grabber!

Some questions to better understand you situation:
- Did you do anything (e.g. try to move it) to Meta Grabber after installing it?
- The files you are trying to rename are located on `D:\`, correct?
- Is the output directory located on `D:\` as well?

I'm using Meta Grabber on macOS and most of the time I'm renaming files on a NAS mounted as a drive (both the files and output dir are on the NAS) which is working perfectly. What Meta Grabber can't do at this point is physically moving files from one drive to another.

Cheers

**Comment by SirFireNewt** [comment]
My main drive is too small to move the media, but I did copy meta
grabber over to my second drive and had basically the same issue.

The files are on `D:\` and I tried the output directory set to
the default, and to a specific directory on `D:\` both fail with
the same issue

The file path appears to be appending the correct directory (or close
to it) to the directory of the tool itself, hence the
`C:\blah\metagrabber\d\media` where it should be `D:\media`

if only windows was more like every other os so we didn't need to deal
with drive labels and using the escape slash in file paths :p

**Comment by andreaswilli** [comment]
Meta Grabber doesn't have to be installed on the same drive as your files. It only can't move files from one drive to another.

The behaviour you are describing might be a problem with how Meta Grabber handles output directory paths. I'll look into it and try to reproduce it.

**Comment by andreaswilli** [comment]
@SirFireNewt Should be fixed in version `0.1.9`. Let me know if it works for you.

**Comment by SirFireNewt** [comment]
Can confirm it works properly now, thanks for the quick fix
